### ISSUE TITLE
"link is not supported" error after using podman compose up --wait

### ISSUE THREAD

**Issue by martin-gif** [monetr/monetr#2309]
After using `podman compose up --wait` i get the following error 
```
Error response from daemon: bad parameter: link is not supported
Error: executing /opt/homebrew/bin/docker-compose up --wait: exit status 1
```
Based on [this website](https://docs.docker.com/engine/network/links/) it seems like `--link` is a legacy feature. Sadly, I can't fix it myself because I'm not that much into docker compose. If I can provide any further information, feel free to ask

**Comment by elliotcourant** [comment]
Given the homebrew path, are you trying to run podman compose on macOS? (homebrew does support linux so wanted to be sure).

I was aware of some significant differences in how podman vs docker worked _years_ ago, but no idea if those are still true today. But I remember podman having some odd nuances on macOS hosts specifically.

**Comment by elliotcourant** [comment]
It looks like the issue is here:

https://github.com/monetr/monetr/blob/de9ccbe8f45623a3c2d955f8b3b71a98378e7942/docker-compose.yaml#L43-L45

I can try to revise the compose file a bit, maybe doing a proper network instead of links is more correct?

**Comment by martin-gif** [comment]
Of course I should have specified my operating system, yes I use a Mac with Podman.

**Comment by martin-gif** [comment]
The service starts after I have replaced the links with a network. 
```
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: superSecretPasswordPleaseChangeMe
      POSTGRES_USER: postgres
      POSTGRES_DB: monetr
    volumes:
      - postgresData:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
        - monetr_netowrk
  valkey:
    image: valkey/valkey:8.0.1
    healthcheck:
      test: [ "CMD", "valkey-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
        - monetr_netowrk
  monetr:
    image: ghcr.io/monetr/monetr:latest
    healthcheck:
      test: "timeout 5s bash -c ':> /dev/tcp/127.0.0.1/4000' || exit 1"
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 5s
    restart: unless-stopped
    command:
      - serve
      # Setup the database and perform migrations.
      - --migrate
      # Since certificates will not have been created, make some.
      - --generate-certificates
    ports:
      - "4000:4000"
    depends_on:
      valkey:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      # Contains certificates generated on startup as well as config
      - monetrData:/etc/monetr
    environment:
      # After creating your own user, it is recommended to disable sign ups if
      # your monetr instance is exposed to the public internet. Otherwise
      # strangers may be able to use your instance themselves.
      MONETR_ALLOW_SIGN_UP: ${MONETR_ALLOW_SIGN_UP:-true}
      MONETR_PG_USERNAME: postgres
      MONETR_PG_PASSWORD: superSecretPasswordPleaseChangeMe
      MONETR_PG_DATABASE: monetr
      MONETR_PG_ADDRESS: postgres
      MONETR_REDIS_ENABLED: "true"
      MONETR_REDIS_ADDRESS: valkey
      MONETR_STORAGE_ENABLED: ${MONETR_STORAGE_ENABLED:-true}
      MONETR_STORAGE_PROVIDER: ${MONETR_STORAGE_PROVIDER:-filesystem}
    networks:
        - monetr_netowrk

volumes:
  monetrData:
  postgresData:
networks:
  monetr_netowrk: 

```
