### ISSUE TITLE
docs: Prevent wrapping of field names on tables describing objects

### ISSUE THREAD

**Issue by elliotcourant** [monetr/monetr#974]
```css
tr td:first-child code {
    white-space: nowrap;
}
```

Should fix it.
